can_purge() - function just virtual - linker problem
- Move function definition outside of header, where definition for base
class is defined and override it.
- For base class adding default constructor and virtual destructor
shouldn't harm
- Failed on linking
```
[ 99%] Linking CXX executable mariadb-backup
Creating mysqld link
[ 99%] Built target mariadbd
/usr/bin/ld: ../libmariadbd.a(log.cc.o): in function `__static_initialization_and_destruction_0(int, int)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.cc:90: undefined reference to `MYSQL_BINARY_LOG::~MYSQL_BINARY_LOG()'
/usr/bin/ld: ../libmariadbd.a(log.cc.o): in function `MYSQL_BINARY_LOG::MYSQL_BINARY_LOG(unsigned int*)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: /home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: ../libmariadbd.a(log.cc.o):(.data.rel.ro._ZTV13MYSQL_BIN_LOG[_ZTV13MYSQL_BIN_LOG]+0x58): undefined reference to `MYSQL_BIN_LOG::can_purge_log(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [libmysqld/examples/CMakeFiles/mariadb-embedded.dir/build.make:138: libmysqld/examples/mariadb-embedded] Error 1
make[1]: *** [CMakeFiles/Makefile2:7170: libmysqld/examples/CMakeFiles/mariadb-embedded.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../../libmysqld/libmariadbd.a(log.cc.o): in function `__static_initialization_and_destruction_0(int, int)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.cc:90: undefined reference to `MYSQL_BINARY_LOG::~MYSQL_BINARY_LOG()'
/usr/bin/ld: ../../libmysqld/libmariadbd.a(log.cc.o): in function `MYSQL_BINARY_LOG::MYSQL_BINARY_LOG(unsigned int*)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: /home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: ../../libmysqld/libmariadbd.a(log.cc.o):(.data.rel.ro._ZTV13MYSQL_BIN_LOG[_ZTV13MYSQL_BIN_LOG]+0x58): undefined reference to `MYSQL_BIN_LOG::can_purge_log(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest/embedded/CMakeFiles/test-connect-t.dir/build.make:104: unittest/embedded/test-connect-t] Error 1
make[1]: *** [CMakeFiles/Makefile2:7251: unittest/embedded/CMakeFiles/test-connect-t.dir/all] Error 2
/usr/bin/ld: ../libmariadbd.a(log.cc.o): in function `__static_initialization_and_destruction_0(int, int)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.cc:90: undefined reference to `MYSQL_BINARY_LOG::~MYSQL_BINARY_LOG()'
/usr/bin/ld: ../libmariadbd.a(log.cc.o): in function `MYSQL_BINARY_LOG::MYSQL_BINARY_LOG(unsigned int*)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: /home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: ../libmariadbd.a(log.cc.o):(.data.rel.ro._ZTV13MYSQL_BIN_LOG[_ZTV13MYSQL_BIN_LOG]+0x58): undefined reference to `MYSQL_BIN_LOG::can_purge_log(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [libmysqld/examples/CMakeFiles/mariadb-test-embedded.dir/build.make:104: libmysqld/examples/mariadb-test-embedded] Error 1
make[1]: *** [CMakeFiles/Makefile2:7197: libmysqld/examples/CMakeFiles/mariadb-test-embedded.dir/all] Error 2
/usr/bin/ld: ../libmariadbd.a(log.cc.o): in function `__static_initialization_and_destruction_0(int, int)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.cc:90: undefined reference to `MYSQL_BINARY_LOG::~MYSQL_BINARY_LOG()'
/usr/bin/ld: ../libmariadbd.a(log.cc.o): in function `MYSQL_BINARY_LOG::MYSQL_BINARY_LOG(unsigned int*)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: /home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: ../libmariadbd.a(log.cc.o):(.data.rel.ro._ZTV13MYSQL_BIN_LOG[_ZTV13MYSQL_BIN_LOG]+0x58): undefined reference to `MYSQL_BIN_LOG::can_purge_log(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [libmysqld/examples/CMakeFiles/mariadb-client-test-embedded.dir/build.make:104: libmysqld/examples/mariadb-client-test-embedded] Error 1
make[1]: *** [CMakeFiles/Makefile2:7224: libmysqld/examples/CMakeFiles/mariadb-client-test-embedded.dir/all] Error 2
/usr/bin/ld: libmariadbd.a(log.cc.o): in function `__static_initialization_and_destruction_0(int, int)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.cc:90: undefined reference to `MYSQL_BINARY_LOG::~MYSQL_BINARY_LOG()'
/usr/bin/ld: libmariadbd.a(log.cc.o): in function `MYSQL_BINARY_LOG::MYSQL_BINARY_LOG(unsigned int*)':
/home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: /home/anel/GitHub/mariadb/server/src/11.4/sql/log.h:1178: undefined reference to `vtable for MYSQL_BINARY_LOG'
/usr/bin/ld: libmariadbd.a(log.cc.o):(.data.rel.ro._ZTV13MYSQL_BIN_LOG[_ZTV13MYSQL_BIN_LOG]+0x58): undefined reference to `MYSQL_BIN_LOG::can_purge_log(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [libmysqld/CMakeFiles/libmysqld.dir/build.make:104: libmysqld/libmariadbd.so.19] Error 1
make[1]: *** [CMakeFiles/Makefile2:7117: libmysqld/CMakeFiles/libmysqld.dir/all] Error 2
Creating mariabackup link
[100%] Built target mariadb-backup
make: *** [Makefile:156: all] Error 2
```